RicohTrainingRegistration/Controllers/DownloadController.cs
using DotNetLib.Storage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RicohTrainingRegistration.Database;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.Controllers
{
    public class DownloadController : ControllerBase
    {
        private readonly RicohDB db;
        private readonly IStorageProvider storage;

        public DownloadController(RicohDB db, IStorageProvider storage)
        {
            this.db = db;
            this.storage = storage;
        }

        [Route("download")]
        public IActionResult Index([FromQuery]int fileId, [FromQuery]int dl = 0)
        {
            var media = db.Media.Find(fileId);
            if (media != null)
            {
                var stream = new MemoryStream();
                if (storage.Read(media.Path, stream))
                {
                    var content = stream.ToArray();
                    if (dl == 1)
                        return File(content, media.ContentType, media.FileName);
                    return File(content, media.ContentType);
                }
            }
            return NotFound();
        }

        [AllowAnonymous]
        [Route("download/faq")]
        public IActionResult Faq(string lang = null)
        {
            CultureInfo culture = null;
            try { culture = CultureInfo.GetCultureInfo(lang); }
            catch { }
            finally { culture = culture ?? CultureInfo.CurrentCulture; }

            lang = culture.TwoLetterISOLanguageName.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh" : "en";
            var docs = db.FaqDocument.Where(x => x.Language.StartsWith(lang)).ToList();
            if (docs.Any())
            {
                var doc = docs.OrderByDescending(x => x.CreatedDate).FirstOrDefault();
                return Index(doc.MediaId);
            }
            return NotFound();
        }
    }
}

RicohTrainingRegistration/Pages/Shared/_Agenda.cshtml
@model RicohTrainingRegistration.Database.TrainingAgenda
@inject Microsoft.Extensions.Localization.IStringLocalizer<Resources.Resource> localizer
@using Localization
@{
    if (Model == null)
    {
        return;
    }

    var agenda = Model;
    var culture = Context.GetCulture().Name;
    var chi = "zh".Equals(Context.GetCulture()?.TwoLetterISOLanguageName, StringComparison.OrdinalIgnoreCase);
    var content = chi ? agenda.ContentChi : agenda.ContentEng;
    var url = chi ? agenda.UrlChi : agenda.UrlEng;
    var label = chi ? agenda.UrlLabelChi : agenda.UrlLabelEng;
    var files = agenda.TrainingAgendaMedia?.Where(a => culture?.Substring(0, 2).Equals(a.Language?.Substring(0, 2), StringComparison.OrdinalIgnoreCase) == true).ToList();
}

<div class="form-group">
    <div class="col-12 col-lg-3">
        <p class="bold">@localizer["Training Agenda:"]</p>
    </div>
    <div class="col-12 col-lg-9">
        <p class="agenda">
            @Html.Paragraph(content)
            <span data-toggle="modal" data-target=".agenda-popup">@localizer["show more"]</span>
        </p>
        @foreach (var file in files)
        {
            var type = "";
            if (file.Media?.ContentType.StartsWith("image", StringComparison.OrdinalIgnoreCase) == true)
            {
                type = "i-jpg";
            }
            else if (file.Media?.ContentType.EndsWith("pdf", StringComparison.OrdinalIgnoreCase) == true)
            {
                type = "i-pdf";
            }
            <p class="@(type)"><a asp-action="Index" asp-controller="Download" asp-route-fileId="@(file.Media?.Id)" target="_blank">@(file.Media?.FileName)</a></p>
        }
        @if (!string.IsNullOrWhiteSpace(label) && !string.IsNullOrWhiteSpace(url))
        {
            <a href="@(url)" target="_blank">@(label ?? url)</a>
        }
    </div>
</div>

RicohTrainingRegistration/Pages/Shared/_AgendaModal.cshtml
@model RicohTrainingRegistration.Database.TrainingAgenda
@inject Microsoft.Extensions.Localization.IStringLocalizer<Resources.Resource> localizer
@using Localization
@{
    if (Model == null)
    {
        return;
    }

    var culture = Context.GetCulture().Name;
    var chi = "zh".Equals(Context.GetCulture()?.TwoLetterISOLanguageName, StringComparison.OrdinalIgnoreCase);
}

<div class="agenda-popup modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="h3">@localizer["Training Agenda"]</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="description">
                    @Html.Paragraph(chi ? Model.ContentChi : Model.ContentEng)
                </p>
            </div>
        </div>
    </div>
</div>

RicohTrainingRegistration/Pages/Shared/_Footer.cshtml
@inject SiteSettings settings
@inject Microsoft.Extensions.Localization.IStringLocalizer<Resources.Resource> res
@using Localization
@{
    var chi = "zh".Equals(Context.GetCulture()?.TwoLetterISOLanguageName, StringComparison.OrdinalIgnoreCase);
}

<footer class="footer-bar">
    <div class="container-fluid flex-row space-between align-center">
        <p>&copy; @(DateTime.Today.Year) Ricoh Hong Kong Limited. <br />@(res["All Rights Reserved."])</p>
        <ul>
            @foreach (var item in settings.FooterLinks)
            {
                if (item.Display == true)
                {
                    var url = chi ? item.UrlChi : item.UrlEng;
                    var label = chi ? item.LabelChi : item.LabelEng;
                    if (!string.IsNullOrWhiteSpace(url) && !string.IsNullOrWhiteSpace(label))
                    {
                        <li><a href="@(url)" target="_blank" rel="noopener noreferrer">@(label)</a></li>
                    }
                }
            }
        </ul>
    </div>
</footer>

RicohTrainingRegistration/Pages/Shared/_GoogleAnalytics.cshtml
@inject Microsoft.Extensions.Configuration.IConfiguration config
@{
    var id = config.GetSection("GoogleAnalytics:TrackingID").Value;
}

<script async src="https://www.googletagmanager.com/gtag/js?id=@(id)"></script>
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', '@(id)');
</script>

RicohTrainingRegistration/Pages/Shared/_Head.cshtml
@inject Microsoft.Extensions.Localization.IStringLocalizer<Resources.Resource> localizer
@using Localization
@{
    var culture = Context.GetCulture().Name;
    var chi = "zh".Equals(Context.GetCulture()?.TwoLetterISOLanguageName, StringComparison.OrdinalIgnoreCase);
}

<head>
    <partial name="_GoogleAnalytics" />
    <!-- meta -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="keywords" content="Ricoh" />
    <meta name="description" content="@(localizer["Head_Description"])" />
    <title>@(localizer["Head_Title"])</title>

    @if (chi)
    {
        <meta property="og:title" content="預約客户培訓課程 | 香港Ricoh" />
        <meta property="og:description" content="預約客户培訓課程，更改／取消預約；理光專員將帶您掌握產品的各種功能，讓您充分了解我們的設備。‎" />
        <meta property="og:site_name" content="香港Ricoh" />
        <meta property="og:image" content="@Url.ContentLink("~/assets/images/1.0_home.png")" />
        <meta property="og:type" content="website" />

        <meta name="twitter:title" content="預約客户培訓課程 | 香港Ricoh" />
        <meta name="twitter:description" content="預約客户培訓課程，更改／取消預約；理光專員將帶您掌握產品的各種功能，讓您充分了解我們的設備。" />
        <meta name="twitter:image" content="@Url.ContentLink("~/assets/images/1.0_home.png")" />
        <meta name="twitter:card" content="summary_large_image" />
    }
    else
    {
        <meta property="og:title" content="Training Registration | Ricoh Hong Kong" />
        <meta property="og:description" content="‎Register the complimentary training of Ricoh Products; reschedule Training. Register the complimentary training to utilize our device to its full capability." />
        <meta property="og:site_name" content="Ricoh Hong Kong" />
        <meta property="og:image" content="@Url.ContentLink("~/assets/images/1.0_home.png")" />
        <meta property="og:type" content="website" />

        <meta name="twitter:title" content="Training Registration | Ricoh Hong Kong" />
        <meta name="twitter:description" content="Register the complimentary training of Ricoh Products; reschedule Training. Register the complimentary training to utilize our device to its full capability." />
        <meta name="twitter:image" content="@Url.ContentLink("~/assets/images/1.0_home.png")" />
        <meta name="twitter:card" content="summary_large_image" />
    }

    <!-- favicon -->
    <link href="~/favicon.ico" rel="icon" />
    <link href="~/favicon.ico" rel="shortcut icon" />
    <link href="~/apple-touch-icon.png" rel="apple-touch-icon" />
    <!-- fonts -->
    <link href="~/lib/font-awesome/css/all.min.css" type="text/css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+HK&display=swap" rel="stylesheet" />
    <!-- css -->
    <link href="~/assets/css/app.min.css" rel="stylesheet" />
    <link href="~/css/style.css" type="text/css" rel="stylesheet" />
</head>

RicohTrainingRegistration/Pages/Shared/_Header.cshtml
@using Localization;
@{
    var culture = Context.GetCulture()?.Name;
}

<header class="header-bar">
    <div class="container-fluid flex-row space-between align-center">
        <div class="logo" data-href="@Url.Page("/Index")/"></div>
        <ul class="lang">
            <li class="@(culture?.StartsWith("zh", StringComparison.OrdinalIgnoreCase) == true ? "active" : "")"><a asp-action="SetLang" asp-controller="Home" asp-route-culture="zh">中<span>文</span></a></li>
            <li class="@(culture == null || culture?.StartsWith("en", StringComparison.OrdinalIgnoreCase) == true ? "active" : "")"><a asp-action="SetLang" asp-controller="Home" asp-route-culture="en">EN<span>GLISH</span></a></li>
        </ul>
    </div>
</header>

RicohTrainingRegistration/Pages/Shared/_IconFail.cshtml
<div class="i-result i-fail">
    <svg xmlns="http://www.w3.org/2000/svg" width="110" height="110" viewBox="0 0 110 110">
        <g fill="none" fill-rule="nonzero">
            <circle cx="55" cy="55" r="55" fill="#B5427C" opacity=".07" />
            <circle cx="55" cy="55" r="32.778" fill="#B5427C" />
            <path fill="#B5427C" d="M55.394 98.889c.703 0 1.273.57 1.273 1.273v8.565c0 .703-.57 1.273-1.273 1.273h-.788c-.703 0-1.273-.57-1.273-1.273v-8.565c0-.703.57-1.273 1.273-1.273h.788zM23.757 85.825l.557.557a1.273 1.273 0 0 1 0 1.8l-6.057 6.057a1.273 1.273 0 0 1-1.8 0l-.557-.557a1.273 1.273 0 0 1 0-1.8l6.057-6.057a1.273 1.273 0 0 1 1.8 0zm64.356-.07l6.056 6.057a1.273 1.273 0 0 1 0 1.8l-.557.557a1.273 1.273 0 0 1-1.8 0l-6.056-6.056a1.273 1.273 0 0 1 0-1.8l.557-.557a1.273 1.273 0 0 1 1.8 0zM9.838 53.334c.703 0 1.273.57 1.273 1.273v.788c0 .703-.57 1.273-1.273 1.273H1.273C.57 56.667 0 56.097 0 55.394v-.788c0-.703.57-1.273 1.273-1.273h8.565zm98.89 0c.702 0 1.272.57 1.272 1.273v.788c0 .703-.57 1.273-1.273 1.273h-8.565c-.703 0-1.273-.57-1.273-1.273v-.788c0-.703.57-1.273 1.273-1.273h8.565zM93.681 15.9l.557.557a1.273 1.273 0 0 1 0 1.8l-6.057 6.057a1.273 1.273 0 0 1-1.8 0l-.557-.557a1.273 1.273 0 0 1 0-1.8l6.057-6.057a1.273 1.273 0 0 1 1.8 0zm-75.494-.07l6.056 6.057a1.273 1.273 0 0 1 0 1.8l-.557.557a1.273 1.273 0 0 1-1.8 0l-6.056-6.056a1.273 1.273 0 0 1 0-1.8l.557-.557a1.273 1.273 0 0 1 1.8 0zM55.394 0c.703 0 1.273.57 1.273 1.273v8.565c0 .703-.57 1.273-1.273 1.273h-.788c-.703 0-1.273-.57-1.273-1.273V1.273c0-.703.57-1.273 1.273-1.273h.788z" />
        </g>
    </svg>
    <span></span>
    <span></span>
</div>

RicohTrainingRegistration/Pages/Shared/_IconLoading.cshtml
<div class="i-loading">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="12" y1="2" x2="12" y2="6" />
        <line x1="16.24" y1="7.76" x2="19.07" y2="4.93" />
        <line x1="18" y1="12" x2="22" y2="12" />
        <line x1="16.24" y1="16.24" x2="19.07" y2="19.07" />
        <line x1="12" y1="18" x2="12" y2="22" />
        <line x1="4.93" y1="19.07" x2="7.76" y2="16.24" />
        <line x1="2" y1="12" x2="6" y2="12" />
        <line x1="4.93" y1="4.93" x2="7.76" y2="7.76" />
    </svg>
</div>

RicohTrainingRegistration/Pages/Shared/_IconSuccess.cshtml
<div class="i-result i-success">
    <svg xmlns="http://www.w3.org/2000/svg" width="110" height="110" viewBox="0 0 110 110">
        <g fill="none" fill-rule="nonzero">
            <circle cx="55" cy="55" r="55" fill="#42B581" opacity=".1" />
            <circle cx="55" cy="55" r="32.778" fill="#42B581" />
            <path fill="#42B581" d="M55.394 98.889c.703 0 1.273.57 1.273 1.273v8.565c0 .703-.57 1.273-1.273 1.273h-.788c-.703 0-1.273-.57-1.273-1.273v-8.565c0-.703.57-1.273 1.273-1.273h.788zM23.757 85.825l.557.557a1.273 1.273 0 0 1 0 1.8l-6.057 6.057a1.273 1.273 0 0 1-1.8 0l-.557-.557a1.273 1.273 0 0 1 0-1.8l6.057-6.057a1.273 1.273 0 0 1 1.8 0zm64.356-.07l6.056 6.057a1.273 1.273 0 0 1 0 1.8l-.557.557a1.273 1.273 0 0 1-1.8 0l-6.056-6.056a1.273 1.273 0 0 1 0-1.8l.557-.557a1.273 1.273 0 0 1 1.8 0zM9.838 53.334c.703 0 1.273.57 1.273 1.273v.788c0 .703-.57 1.273-1.273 1.273H1.273C.57 56.667 0 56.097 0 55.394v-.788c0-.703.57-1.273 1.273-1.273h8.565zm98.89 0c.702 0 1.272.57 1.272 1.273v.788c0 .703-.57 1.273-1.273 1.273h-8.565c-.703 0-1.273-.57-1.273-1.273v-.788c0-.703.57-1.273 1.273-1.273h8.565zM93.681 15.9l.557.557a1.273 1.273 0 0 1 0 1.8l-6.057 6.057a1.273 1.273 0 0 1-1.8 0l-.557-.557a1.273 1.273 0 0 1 0-1.8l6.057-6.057a1.273 1.273 0 0 1 1.8 0zm-75.494-.07l6.056 6.057a1.273 1.273 0 0 1 0 1.8l-.557.557a1.273 1.273 0 0 1-1.8 0l-6.056-6.056a1.273 1.273 0 0 1 0-1.8l.557-.557a1.273 1.273 0 0 1 1.8 0zM55.394 0c.703 0 1.273.57 1.273 1.273v8.565c0 .703-.57 1.273-1.273 1.273h-.788c-.703 0-1.273-.57-1.273-1.273V1.273c0-.703.57-1.273 1.273-1.273h.788z" />
        </g>
    </svg>
    <span></span>
    <span></span>
</div>

RicohTrainingRegistration/Pages/Shared/_Js.cshtml
<!-- js -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="~/assets/js/jquery.nicescroll.min.js"></script>
<script src="~/assets/js/bundle.min.js"></script>

RicohTrainingRegistration/Pages/Shared/_LanguageSwitch.cshtml
@using Localization
@{
    var culture = Context.GetCulture()?.Name;
    var cultures = Context.GetSupportedCultures()
        .Select(c => new SelectListItem { Text = c.DisplayName, Value = c.Name })
        .ToList();
}

<form method="post" asp-controller="Home" asp-action="SetLang">
    <select id="LanguageSwitch" class="form-control" onchange="this.form.submit();" asp-for="@culture" asp-items="cultures"></select>
</form>

RicohTrainingRegistration/Pages/Shared/_Layout.cshtml
@using Localization
@inject Microsoft.Extensions.Localization.IStringLocalizer<Resources.Resource> localizer
@{
    var culture = Context.GetCulture().Name;
}

<!DOCTYPE html>
<html lang="zh-Hant">
<partial name="_Head" />

<body>
    @if (ViewBag.HideHeader != true)
    {
        <partial name="_Header" />
    }

    @RenderBody()

    <partial name="_Footer" />
    <partial name="_Js" />

    <script src="~/lib/bootbox/bootbox.min.js"></script>
    @if (culture?.StartsWith("zh", StringComparison.OrdinalIgnoreCase) == true)
    {
        <script>
            bootbox.addLocale('zh', {
                OK: '@Html.Raw(localizer["OK"]?.Value)',
                CANCEL: '@Html.Raw(localizer["Cancel"]?.Value)',
                CONFIRM: '@Html.Raw(localizer["Confirm"]?.Value)'
            });
            bootbox.setLocale('zh');
        </script>
    }
    <script src="~/js/button.js"></script>
    <script src="~/js/ajax.js"></script>
    @RenderSection("PageScripts", false)

    <script>
        $(document).ready(function () {
            Button.listen();

            @RenderSection("InitScripts", false)
        })
    </script>
</body>
</html>

RicohTrainingRegistration/Pages/Shared/_RecaptchaMessage.cshtml
@using Microsoft.Extensions.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IStringLocalizer<Resources.Resource> Localize
@inject IHtmlLocalizer<Resources.Resource> LocalizeHtml

@LocalizeHtml["This site is protected by reCAPTCHA and the <a href=\"{0}\" target=\"_blank\">Google Privacy Policy</a> and <a href=\"{1}\" target=\"_blank\">Terms of Service</a> apply.",
    Localize["https://www.google.com/intl/en-GB/policies/privacy/"],
    Localize["https://www.google.com/intl/en-GB/policies/terms/"]
]

RicohTrainingRegistration/Pages/Shared/_ScrollTop.cshtml
<div class="scroll-top">
    <img src="~/assets/images/icon-arrow-top-red.svg" alt="" />
</div>