RicohTrainingRegistration/Controllers/ApiController.cs
using DotNetLib;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using RicohTrainingRegistration.Database;
using RicohTrainingRegistration.Resources;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class ApiController : ControllerBase
    {
        private readonly ILogger<ApiController> logger;
        private readonly IStringLocalizer<Resource> localizer;
        private readonly RicohDB db;
        private readonly SiteSettings settings;

        public ApiController(ILogger<ApiController> logger, IStringLocalizer<Resource> localizer, RicohDB db, SiteSettings settings)
        {
            this.logger = logger;
            this.localizer = localizer;
            this.db = db;
            this.settings = settings;
        }

        private string Localize(string name, params object[] arguments)
        {
            if (name != null)
                return localizer.GetString(name, arguments);
            return name;
        }

        [Route("api/training/date")]
        public IActionResult TrainingDate([FromQuery]string district)
        {
            if (!new[] { "hk", "kln", "nt" }.Contains(district?.ToLower()))
                return new JsonResult(new { });

            var orderId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var expiryDate = db.MachineInstallationDate.Find(orderId)?.FreeTrainingEndDate;

            var modelId = User.FindFirst("ModelId")?.Value;

            DateTime startDate, endDate;
            var items = db.GetTodayScheduleItems(modelId, district, out startDate, out endDate);
            var totalDays = (int)(endDate - startDate).TotalDays;
            var dates = Enumerable.Range(0, totalDays).Select(x => startDate.AddDays(x)).ToList();
            var datesDisabled = dates.Where(x => !items.Any(d => d.Date == x && d.ScheduleItemSlot.Any(s => d.IsUseCustom == s.IsCustom)) || x > expiryDate).ToList();
            startDate = dates.Any(x => !datesDisabled.Contains(x)) ? dates.First(x => !datesDisabled.Contains(x)) : startDate;

            if (items.Any())
            {
                var maxDate = items.Max(x => x.Date);
                endDate = endDate > maxDate ? maxDate : endDate;
                datesDisabled = datesDisabled.Where(x => x < maxDate).ToList();
            }

            return new JsonResult(new
            {
                startDate = startDate.ToString("yyyy-MM-dd"),
                endDate = endDate.AddDays(-1).ToString("yyyy-MM-dd"),
                datesDisabled = datesDisabled.Select(x => x.ToString("yyyy-MM-dd"))
            });
        }

        [Route("api/training/timeslot")]
        public IActionResult TrainingTimeslot([FromQuery]string district, [FromQuery]string date)
        {
            if (!new[] { "hk", "kln", "nt" }.Contains(district?.ToLower())
                || !DateTime.TryParseExact(date, "yyyy-MM-dd", System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeStyles.None, out DateTime trainingDate))
                return new JsonResult(Enumerable.Empty<object>());

            var orderId = User.OrderId();
            var reg = db.RegistrationTimeslot.FirstOrDefault(x => x.OrderId == orderId);

            var slots = db.ScheduleItemSlot
                .Where(x => x.ScheduleItem.District == district && x.ScheduleItem.Date == trainingDate)
                .Where(x => x.IsCustom == x.ScheduleItem.IsUseCustom)
                .ToList();
            var data = slots.GroupBy(x => x.Timeslot).Select(x => new
            {
                value = x.Key,
                isEnabled = x.Any(s => s.RegistrationId == null || s.RegistrationId == reg?.Id)
            }).OrderBy(x => x.value).ToList();

            return new JsonResult(data);
        }

        [HttpPost]
        [Route("api/training/cancel")]
        public IActionResult CancelTraining()
        {
            var orderId = User.OrderId();
            var serialNo = User.SerialNo();
            logger.LogDebug("Request cancellation of training for serial no. {0} ({1})", serialNo, orderId);

            var registration = db.Registration.SingleOrDefault(x => x.OrderId == orderId);
            if (registration == null)
            {
                logger.LogInformation("Registration not found for serial no. {0} ({1})", serialNo, orderId);
                return BadRequest(new { message = Localize("Registration could not be found.") });
            }

            if (registration.Status != RegistrationStatus.Submitted && registration.Status != RegistrationStatus.Rescheduled)
            {
                logger.LogInformation("Invalid registration status for cancellation for serial no. {0} ({1}) - {2}", serialNo, orderId, registration.Status);
                return BadRequest(new { message = Localize("Registration could not be found."), redirect = Url.Page("/Logout"), redirectType = "replace" });
            }

            db.ScheduleItemSlot.Where(x => x.Registration.OrderId == orderId)
                .ToList()
                .ForEach(x => x.RegistrationId = null);

            registration.Status = RegistrationStatus.Cancelled;
            db.SaveChanges();

            // send email
            var id = registration.Id;
            var r = db.RegistrationTimeslot.Find(id);
            var sn = SecurityHelper.Encrypt(RegistrationPassphrase.Register, r.SerialNo);
            var regDate = db.MachineInstallationDate.FirstOrDefault(x => x.OrderId == orderId);
            var zh = System.Globalization.CultureInfo.CurrentCulture.Name.StartsWith("zh", StringComparison.OrdinalIgnoreCase);
            db.AddEmailRequest(
                EmailTemplateId.TRAINING_CANCEL,
                new
                {
                    CUSTOMER_NAME = r.CompanyName,
                    CONTACT_NAME = r.ContactName,
                    PHONE_NO = r.PhoneNo,
                    MODEL_NO = r.ModelId,
                    SERIAL_NO = r.SerialNo,
                    TRAINING_DATE = string.Format("{0:yyyy/MM/dd}", r.ScheduleDate ?? r.TrainingDate),
                    TRAINING_TIMESLOT = r.ScheduleTimeslot ?? r.TrainingTimeslot,
                    VENUE_ADDRESS = r.VenueAddress?.Trim(),
                    LOGIN_URL = Url.Action("Invite", "Home", new { sn }, Request.Scheme, Request.Host.Value),
                    REG_DATE = string.Format("{0:yyyy/MM/dd}", regDate?.FreeTrainingEndDate),
                    DISTRICT = Localize(db.GetDistrictList().FirstOrDefault(x => x.Id.EqualsIgnoreCase(r.ScheduleDistrict ?? r.District))?.Label),
                    NO_SUITABLE_CHOICE = r.TrainingDatePreferable == true ? "Y" : "N",
                    NO_SUITABLE_CHOICE_REMARK = string.IsNullOrWhiteSpace(r.TrainingDateRemarks) ? Localize("-") : r.TrainingDateRemarks,
                    ATTENDEES = db.GetAttendeeList(zh).FirstOrDefault(x => x.Id.EqualsIgnoreCase(r.Attendees))?.Label,
                    ATTENDEES_NOTE = db.GetAttendeeList(zh).FirstOrDefault(x => x.Id.EqualsIgnoreCase(r.Attendees))?.Note,
                    OS = db.GetOperatingSystemList(zh).FirstOrDefault(x => x.Id.EqualsIgnoreCase(r.OperatingSystem))?.Label,
                    COMPANY_NAME = r.CompanyName,
                    EMAIL = r.Email,
                    REMARKS = string.IsNullOrWhiteSpace(r.Remarks) ? Localize("-") : r.Remarks
                },
                r.Email,
                r.ContactName
            );
            db.SaveChanges();

            // clear remind email
            var templateId = EmailTemplateId.TRAINING_REMIND;
            db.MachineInstallationEmail.Where(x => x.OrderId == orderId && x.EmailTemplateId == templateId).ToList()
                .ForEach(x => x.IsActive = false);
            db.SaveChanges();

            return Ok(new
            {
                success = true,
                redirect = Url.Page("/Reschedule/Cancel")
            });
        }
    }
}

RicohTrainingRegistration/Pages/Shared/DisplayTemplates/ReschedulePreview.cshtml
@model RicohTrainingRegistration.Pages.Reschedule.PreviewModel
@using Microsoft.Extensions.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Localization
@inject IStringLocalizer<Resources.Resource> Localize
@inject IHtmlLocalizer<Resources.Resource> LocalizeHtml
@{
    var chi = "zh".Equals(Context.GetCulture()?.TwoLetterISOLanguageName, StringComparison.OrdinalIgnoreCase);
    var landing = Model.IsLanding;
}

<div class="@(Model.IsRequest ? "reschedule" : "registration") container-wrapper pt-0">
    <div class="page-banner d-flex justify-content-center align-items-end">
        <div class="bg"></div>
        <div class="container-fluid d-flex">
            <div class="row justify-content-center align-items-start">
                <div class="col-12 col-xl-6">
                    <div class="image-wrapper">
                        <img src="~/assets/images/2.0_page.png" alt="Training Registration" class="img-fluid" />
                    </div>
                </div>
                <div class="col-12 col-xl-6">
                    <div class="text-wrapper">
                        <h1 class="h1">@LocalizeHtml["Reschedule /<br />Cancel Training"]</h1>
                        <div class="serial-number i-check">@Localize["Serial no.: {0}", Model.Install?.SerialNo]</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        @if (Model.IsRequest)
        {
            <form id="frm-request" asp-page="/Reschedule/Request" class="custom-form mw-md background-light-pink">
                <div class="icon-wrapper">
                    <img src="~/assets/images/icon-fail.svg" class="img-fluid" />
                </div>
                <h2 class="h2">@Localize["Reschedule fail"]</h2>
                <p class="description">
                    @LocalizeHtml["Please reschedule your appointment at least one day before the date of appointment.<br />If you are unable to attend, please leave message below, we will contact you shortly."]
                </p>
                <textarea name="Message" cols="30" rows="4" maxlength="100" placeholder="@Localize["Leave a message here..."]"></textarea>
                <div class="btn-group justify-content-center align-items-center">
                    <button type="submit" class="btn btn-primary i-arrow">@Localize["Send Request"]</button>
                </div>
            </form>
        }
        <div class="page-header">
            <h2 class="h2">@Localize["Training Registration"]</h2>
            <p class="mb-t">@Localize[landing ? "Please click \"Reschedule\" to edit your information." : "Please click \"Confirm\" after you checked your information."]</p>
            <div class="custom-wrapper mw-md">
                <div class="row">
                    <div class="form-group">
                        <div class="col-12 col-lg-3">
                            <p class="bold">@Localize["Model:"]</p>
                        </div>
                        <div class="col-12 col-lg-9">
                            <p>@(Model.Training?.ModelName)</p>
                        </div>
                    </div>
                    <partial name="_Agenda" model="Model.Agenda" />
                </div>
            </div>
        </div>
        <div class="custom-toggle-wrapper mw-md">
            <h3 class="h3">@Localize["Training Preferences"]</h3>
            <button class="custom-toggle-btn toggle @(landing ? "collapsed" : "")" type="button" data-toggle="collapse" data-target="#trainingPreference"
                    aria-expanded="false" aria-controls="collapseExample">
                <span></span>
            </button>
        </div>
    </div>

    <form id="frm1" method="post" class="custom-form">
        <input asp-for="Session" type="hidden" />
        <div class="collapse @(landing ? "" : "show")" id="trainingPreference">
            <div class="container-fluid">
                <div class="mw-md">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-12">
                                <label>@Localize["Training Venue"]*</label>
                                <div class="text-box">@(Model.Register.VenueAddress)</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-12">
                                <label>@Localize["District"]*</label>
                                <div class="text-box">@(Model.Register.DistrictDisplay)</div>
                            </div>
                        </div>
                        <div class="form-group">
                            @if (string.IsNullOrEmpty(Model.Register.TrainingTimeslot))
                            {
                                <div class="col-12">
                                    <label>@Localize["Cannot find your desired training time"]</label>
                                    <div class="text-box">
                                        @Html.Raw(Model.Register.TrainingDateRemarks?.Replace(Environment.NewLine, "<br />"))
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="col-12 col-lg-6">
                                    <label>@Localize["Training Date"]*</label>
                                    <div class="text-box">@(Model.Register.TrainingDate)</div>
                                </div>
                                <div class="col-12 col-lg-6">
                                    <label>@Localize["Preferred Timeslot"]*</label>
                                    <div class="text-box">@(Model.Register.TrainingTimeslot)</div>
                                </div>
                            }
                        </div>
                        <div class="form-group">
                            <div class="col-12 col-lg-6">
                                <label>@Localize["No. of Attendees"]*</label>
                                <div class="text-box">@(Model.Register.AttendeesDisplay)</div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <label>@Localize["Operating System"]*</label>
                                <div class="text-box">@(Model.Register.OperatingSystemDisplay)</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="custom-toggle-wrapper mw-md">
                <h3 class="h3">@Localize["Contact Info"]</h3>
                <button class="custom-toggle-btn @(landing ? "toggle collapsed" : "")" type="button" data-toggle="collapse" data-target="#contactInfo"
                        aria-expanded="false" aria-controls="collapseExample">
                    <span></span>
                </button>
            </div>
            <div class="collapse @(landing ? "" : "show")" id="contactInfo">
                <div class="mw-md">
                    <div class="row">
                        <div class="form-group">
                            <div class="col-12">
                                <label>@Localize["Company Name"]*</label>
                                <div class="text-box">@(Model.Register.CompanyName)</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-12 col-lg-6">
                                <label>@Localize["First Name"]*</label>
                                <div class="text-box">@(Model.Register.FirstName)</div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <label>@Localize["Last Name"]*</label>
                                <div class="text-box">@(Model.Register.LastName)</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-12 col-lg-6">
                                <label>@Localize["Phone No."]*</label>
                                <div class="custom-number">
                                    <div class="text-box">@(Model.ShowPhoneNo ? Model.Register.PhoneNo : Model.Register.PhoneNo?.MaskPhoneNo())</div>
                                    <span>+852</span>
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <label>@Localize["Email Address"]*</label>
                                <div class="text-box">@(Model.ShowEmail ? Model.Register.Email : Model.Register.Email?.MaskEmail())</div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-12">
                                <label>@Localize["Remarks"]</label>
                                <div class="text-box">
                                    @Html.Raw(Model.Register.Remarks?.Replace(Environment.NewLine, "<br />"))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            @if (!Model.IsRequest)
            {
                <div class="mw-md">
                    <div class="btn-group justify-content-center justify-content-lg-end align-items-center">
                        @if (landing)
                        {
                            <button type="button" class="btn btn-primary i-arrow" data-href="@Url.Page("/Reschedule/Form")">@Localize["Re-schedule"]</button>
                            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target=".custom-popup">@Localize["Cancel training"]</button>
                        }
                        else
                        {
                            <button type="submit" class="btn btn-primary i-arrow">@Localize["Confirm"]</button>
                            <button type="button" class="btn btn-secondary" data-href="@Url.Page("/Reschedule/Form", new { display = "revise" })">@Localize["Back"]</button>
                        }
                    </div>
                </div>
            }
        </div>
    </form>
</div>
<partial name="_ScrollTop" />

@if (landing)
{
    <div class="custom-popup modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon"></div>
                </div>
                <div class="modal-body">
                    <h2 class="h2 mb-3">@Localize["Cancel Training?"]</h2>
                    <p class="description">@Localize["Are you sure you want to cancel training?"]</p>
                </div>
                <div class="btn-group justify-content-center justify-content-lg-end align-items-center">
                    <form id="frm-cancel" method="post" asp-action="CancelTraining" asp-controller="Api">
                        <button type="submit" class="btn btn-primary">@Localize["Confirm"]</button>
                        <button type="button" class="btn btn-third" data-dismiss="modal">@Localize["Back"]</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

<partial name="_AgendaModal" model="Model.Agenda" />