RicohTrainingRegistration.CMS/Models/CustomScheduleEditModel.cs
using RicohTrainingRegistration.Database;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.CMS.Models
{
    public class CustomScheduleEditModel
    {
        public int Id { get; set; }

        [Display(Name = "Date")]
        [Required]
        public DateTime? Date { get; set; }

        [Display(Name = "District")]
        [Required]
        public string District { get; set; }

        [Display(Name = "Default Timeslots")]
        public List<CustomScheduleSlotEditModel> DefaultTimeslots { get; internal set; }

        [Display(Name = "Custom Timeslots")]
        public List<CustomScheduleSlotEditModel> CustomTimeslots { get; set; }

        public bool? IsUseCustom { get; set; }

        [StringLength(200)]
        public string Remark { get; set; }
    }

    public class CustomScheduleSlotEditModel
    {
        [Required]
        public string Timeslot { get; set; }

        [Required]
        [Range(0, 99, ErrorMessage = "Invalid quota value")]
        public int Quota { get; set; }

        public List<DotNetLib.Datatable.DtRowAction> Registrations { get; set; }

        public string StartTime => string.Format("{0:HH:mm}", ScheduleItemSlot.ParseTime(Timeslot?.Split(" - ").FirstOrDefault()));
        public string EndTime => string.Format("{0:HH:mm}", ScheduleItemSlot.ParseTime(Timeslot?.Split(" - ").Skip(1).FirstOrDefault()));
    }
}

RicohTrainingRegistration.CMS/Models/DashboardModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.CMS.Models
{
    public class DashboardModel
    {
        public DateTime Date { get; set; }
        public int AvailableTimeslot { get; set; }
        public int InstallationEntitled { get; set; }
        public int SentInvitation { get; set; }

        public int RegistrationPreferred { get; set; }
        public int RegistrationScheduled { get; set; }
        public int Registration => RegistrationPreferred + RegistrationScheduled;

        public int TrainingProvided { get; set; }
        public int NotYetRegistered { get; set; }
        public int AvailableTimeslotLeft { get; set; }
    }
}

RicohTrainingRegistration.CMS/Models/EmailSettingEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.CMS.Models
{
    public class EmailSettingEditModel
    {
        public List<string> TrainerAddresses { get; set; }

        [Display(Name = "From (Display)")]
        public string From { get; set; }
        
        [Display(Name = "From Address")]
        [EmailAddress]
        public string FromAddress { get; set; }

        public List<string> ReplyToAddresses { get; set; }

        [Display(Name = "Return Path")]
        [EmailAddress]
        public string ReturnAddress { get; set; }
    }
}

RicohTrainingRegistration.CMS/Models/EmailTemplateEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.CMS.Models
{
    public class EmailTemplateEditModel
    {
        public string Id { get; set; }
        
        public string Name { get; set; }
        
        [Display(Name = "Subject (Eng)")]
        [StringLength(100)]
        public string SubjectEng { get; set; }
        
        [Display(Name = "Subject (Chi)")]
        [StringLength(100)]
        public string SubjectChi { get; set; }
        
        [Display(Name = "Content (Eng)")]
        [StringLength(int.MaxValue)]
        public string ContentEng { get; set; }

        [Display(Name = "Content (Chi)")]
        [StringLength(int.MaxValue)]
        public string ContentChi { get; set; }
        
        public bool? SendToTrainers { get; set; }
    }
}

RicohTrainingRegistration.CMS/Models/MediaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RicohTrainingRegistration.CMS.Models
{
    public class MediaModel
    {
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Url { get; set; }
        public string ContentType { get; set; }
        public int ContentLength { get; set; }
        public string Language { get; set; }
    }
}

RicohTrainingRegistration.CMS/Controllers/TrainingModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DotNetLib;
using DotNetLib.Datatable;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RicohTrainingRegistration.CMS.Models;
using RicohTrainingRegistration.Database;

namespace RicohTrainingRegistration.CMS.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class TrainingModelController : ControllerBase
    {
        private readonly RicohDB db;

        public TrainingModelController(RicohDB db)
        {
            this.db = db;
        }

        [Route("training/model/list")]
        public IActionResult List(DtRequest<TrainingModelFilter> model)
        {
            var query = db.TrainingModel.Include(x => x.TrainingAgenda).AsQueryable();
            var recordsTotal = query.Count();

            if (model.SearchValue.IsNotNullAndWhiteSpace())
            {
                var search = model.SearchValue;
                query = query.Where(x => x.ModelId.Contains(search) || x.ModelName.Contains(search));
            }

            if (model.Params?.FreeTraining.Any() == true)
            {
                var display = model.Params.FreeTraining.Select(x => "Entitled".EqualsIgnoreCase(x)).ToArray();
                query = query.Where(x => display.Contains(x.IsFreeTraining));
            }

            var result = model.GetOrderable(query)
                .OrderDefaults()
                .Order("id", x => x.ModelId)
                .Order("name", x => x.ModelName)
                .Order("agenda", x => x.TrainingAgenda.Title)
                .Order("isFree", x => !x.IsFreeTraining)
                .GetResult(recordsTotal);

            return Ok(
                result.As(x => new
                {
                    id = x.ModelId,
                    name = x.ModelName,
                    isFree = x.IsFreeTraining,
                    openedDays = x.OpenedDays,
                    agenda = x.TrainingAgenda != null ? new { title = x.TrainingAgenda.Title, url = Url.Page("/Training/Agenda/Edit", new { id = x.TrainingAgenda.Id }) } : null,
                    retrievedDate = x.RetrievedDate,
                    updatedDate = x.UpdatedDate,
                    editUrl = Url.Action("Edit", new { modelId = x.ModelId })
                })
            );
        }

        [HttpPost]
        [Route("training/model")]
        public IActionResult Edit(string modelId, TrainingModelEditModel model)
        {
            if (ModelState.IsValid)
            {
                var entity = db.TrainingModel.Find(modelId);
                if (entity != null)
                {
                    entity.IsFreeTraining = model.IsFree == true;
                    entity.OpenedDays = model.OpenedDays.Value;
                    db.SaveChanges(JobLogTitle.SaveTrainingModel);
                    return Ok(new { success = true, message = "Item saved." });
                }
                return BadRequest(new { message = "Item not found" });
            }
            return BadRequest(new { message = ModelState.FirstErrorMessage() });
        }

        [HttpDelete]
        [Route("training/model/{modelId}")]
        public IActionResult Delete(string modelId)
        {
            var model = db.TrainingModel.Find(modelId);
            if (model != null)
            {
                db.TrainingModel.Remove(model);
                db.SaveChanges(JobLogTitle.DeleteTrainingModel);
                return Ok(new { success = true, message = "Item deleted." });
            }
            return BadRequest(new { message = "Item not found" });
        }
    }
}

RicohTrainingRegistration.CMS/Pages/Training/Agenda/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using DotNetLib;
using DotNetLib.Storage;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RicohTrainingRegistration.CMS.Models;
using RicohTrainingRegistration.Database;

namespace RicohTrainingRegistration.CMS.Pages.Training.Agenda
{
    public class EditModel : PageModel
    {
        private readonly RicohDB DB;
        private readonly IStorageProvider Storage;

        public EditModel(RicohDB db, IStorageProvider storage)
        {
            DB = db;
            Storage = storage;
        }

        [BindProperty]
        public TrainingAgendaEditModel Agenda { get; set; }

        public List<SelectListItem> ModelList { get; internal set; }
        public List<MediaModel> MediaList { get; internal set; }

        public IActionResult OnGet(int? id)
        {
            Agenda = new TrainingAgendaEditModel();
            if (id > 0)
            {
                var agenda = DB.TrainingAgenda.Include(x => x.TrainingModel).SingleOrDefault(x => x.Id == id);
                if (agenda != null)
                {
                    agenda.Populate(Agenda);
                    Agenda.Models = agenda.TrainingModel.Select(x => x.ModelId).ToList();

                }
                else
                    return NotFound();
            }

            var agendaId = Agenda.Id;

            // model drop down list
            var models = DB.TrainingModel.ToList();
            ModelList = models.Select(x => new SelectListItem
            {
                Text = $"{x.ModelId} - {x.ModelName}",
                Value = x.ModelId,
                Disabled = x.TrainingAgendaId.HasValue && x.TrainingAgendaId != agendaId
            }).ToList();

            // media list
            if (agendaId > 0)
                MediaList = DB.TrainingAgendaMedia.Include(x => x.Media)
                    .Where(x => x.TrainingAgendaId == agendaId)
                    .ToList()
                    .Select(x => new MediaModel
                    {
                        Id = x.Media.Id,
                        FileName = x.Media.FileName,
                        Url = Url.Action("Get", "Media", new { x.Media.Id }),
                        ContentType = x.Media.ContentType,
                        ContentLength = x.Media.ContentLength,
                        Language = x.Language
                    }).ToList();
            else
                MediaList = new List<MediaModel>();

            return Page();
        }

        public IActionResult OnPost(int? id)
        {
            if (ModelState.IsValid)
            {
                TrainingAgenda agenda;
                if (id > 0)
                {
                    agenda = DB.TrainingAgenda.Include(x => x.TrainingAgendaMedia).ThenInclude(x => x.Media).SingleOrDefault(x => x.Id == id);
                    if (agenda == null)
                        return this.Fail("Record not found.");
                }
                else
                    agenda = DB.TrainingAgenda.Add(new TrainingAgenda()).Entity;

                var agendaId = agenda.Id;

                // training models
                var models = Agenda.Models ?? new List<string>();
                var modelList = DB.TrainingModel.Where(x => x.TrainingAgendaId == null || x.TrainingAgendaId == agendaId).ToList();
                var trainingModels = modelList.Where(x => models.Contains(x.ModelId)).ToList();
                var removeTrainingModels = modelList.Where(x => !models.Contains(x.ModelId)).ToList();

                // attachments
                List<TrainingAgendaMedia> attachments = Enumerable.Empty<TrainingAgendaMedia>()
                    .Concat(CreateAttachments(agenda, Agenda.AttachmentsEng, TrainingAgendaMedia.English))
                    .Concat(CreateAttachments(agenda, Agenda.AttachmentsChi, TrainingAgendaMedia.Chinese))
                    .ToList();

                // remove attachments
                var removeAttachments = agenda.TrainingAgendaMedia.Where(x => Agenda.RemoveAttachments?.Contains(x.MediaId) == true
                    //|| (x.Language == TrainingAgendaMedia.English && attachments.Any(a => a.Language == TrainingAgendaMedia.English))
                    //|| (x.Language == TrainingAgendaMedia.Chinese && attachments.Any(a => a.Language == TrainingAgendaMedia.Chinese))
                ).ToList();

                // update db records
                Agenda.PopulateExcept(agenda, "Id");
                trainingModels.ForEach(x => x.TrainingAgenda = agenda);
                removeTrainingModels.ForEach(x => x.TrainingAgenda = null);
                DB.TrainingAgendaMedia.AddRange(attachments);
                DB.TrainingAgendaMedia.RemoveRange(removeAttachments);
                DB.Media.RemoveRange(removeAttachments.Select(x => x.Media));
                DB.SaveChanges(JobLogTitle.SaveTrainingAgenda);

                return this.Ok(
                    message: "Save success.",
                    redirect: Url.Page("/Training/Agenda/Edit", new { id = agenda.Id })
                );
            }
            return this.Fail(ModelState.FirstErrorMessage());
        }

        private IEnumerable<TrainingAgendaMedia> CreateAttachments(TrainingAgenda agenda, IEnumerable<IFormFile> files, string language)
        {
            files = files ?? Enumerable.Empty<IFormFile>();
            int i = 1;
            foreach (var file in files)
            {
                var media = new Media
                {
                    FileName = file.FileName,
                    Path = string.Join("/", "agenda", Path.GetRandomFileName()),
                    ContentLength = (int)file.Length,
                    ContentType = file.ContentType
                };
                if (Storage.Create(media.Path, file.OpenReadStream()))
                    yield return new TrainingAgendaMedia
                    {
                        TrainingAgenda = agenda,
                        Media = media,
                        Language = language,
                        DisplayOrder = i++
                    };
            }
        }
    }
}

RicohTrainingRegistration.CMS/Pages/Training/Agenda/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RicohTrainingRegistration.CMS.Pages.Training.Agenda
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RicohTrainingRegistration.CMS/Pages/Training/Holiday/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RicohTrainingRegistration.CMS.Models;
using RicohTrainingRegistration.Database;

namespace RicohTrainingRegistration.CMS.Pages.Training.Holiday
{
    public class EditModel : PageModel
    {
        private readonly RicohDB DB;

        public EditModel(RicohDB db)
        {
            DB = db;
        }

        [BindProperty]
        public HolidayEditModel Holiday { get; set; }

        public IActionResult OnGet(int? id)
        {
            Holiday = new HolidayEditModel();
            if (id > 0)
            {
                var holiday = DB.Holiday.Find(id);
                if (holiday != null)
                {
                    Holiday.Id = holiday.Id;
                    Holiday.Name = holiday.Name;
                    Holiday.StartDate = holiday.StartDate;
                    Holiday.EndDate = holiday.EndDate;
                    Holiday.Type = holiday.Type;
                }
                else
                    return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost(int? id)
        {
            if (ModelState.IsValid)
            {
                if (Holiday.StartDate > Holiday.EndDate)
                    return this.Fail("Date is not valid.");

                Database.Holiday model;
                if (id > 0)
                {
                    model = DB.Holiday.Find(id);
                    if (model == null)
                        return this.Fail("Record not found.");
                }
                else
                    model = DB.Holiday.Add(new Database.Holiday { Type = HolidayType.Manual }).Entity;

                model.Name = Holiday.Name;
                model.StartDate = Holiday.StartDate.Value;
                model.EndDate = Holiday.EndDate.Value;

                DB.SaveChanges(JobLogTitle.SaveHoliday);
                return this.Ok(
                    message: "Save Success",
                    redirect: Url.Page($"/Training/Holiday/Edit", new { id = model.Id })
                );
            }
            return this.Fail(ModelState.FirstErrorMessage());
        }
    }
}

RicohTrainingRegistration.CMS/Pages/Training/Holiday/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RicohTrainingRegistration.CMS.Pages.Training.Holiday
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

RicohTrainingRegistration.CMS/Pages/Training/Model/Index.cshtml
@page
@inherits DefaultPageBase
@model RicohTrainingRegistration.CMS.Pages.Training.Model.IndexModel
@{
    PageTitle("Training Models");
    PageHeading("Training Models");
    ActiveMenus("Model");
    Breadcrumbs(
        new Breadcrumb("Training Models")
    );

    UseDatatable();
}

<div class="box box-solid">
    <div class="box-body">
        <div class="box box-default box-solid">
            <div class="box-header with-border">
                <h3 class="box-title">Filters</h3>
            </div>
            <div class="box-body">
                <form id="frm1" method="post" class="form-horizontal">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label col-md-3">Free Training</label>
                                <div class="col-md-6">
                                    <div class="checkbox-list">
                                        <label class="checkbox-inline"><input type="checkbox" name="FreeTraining[]" value="ENTITLED" checked /> Entitled</label>
                                        <label class="checkbox-inline"><input type="checkbox" name="FreeTraining[]" value="WITHDRAWN" checked /> Withdrawn</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="table-responsive">
            <table id="dt1" class="table table-bordered" style="width:100%" data-dt-ajax="@Url.Action("List", "TrainingModel")">
                <thead>
                    <tr>
                        <th><span title="Model No.">Model</span></th>
                        <th><span title="Model Name">Name</span></th>
                        <th><span title="Entitled free training">Free Training</span></th>
                        <th><span title="Days opened for registration">Opened Days</span></th>
                        <th><span title="Agenda">Agenda</span></th>
                        <th><span title="Retrieved date">Retrieved</span></th>
                        <th><span title="Last modified date">Modified</span></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>
@if (Model.LastRetrievedDate.HasValue)
{
    <div class="text-right text-muted text-sm" style="margin:-15px 0 5px">Last retrieved: <span class="text-bold" data-last-retrieved-date="@(string.Format("{0:yyyy-MM-dd HH:mm:ss}", Model.LastRetrievedDate))"></span></div>
}

<partial name="_Edit" model="new RicohTrainingRegistration.CMS.Models.TrainingModelEditModel()" />

@section PageScripts
{
    <script src="~/js/pages/training/model/index.js"></script>
}

<script>
    @section InitScripts
    {
    Page.init();
    }
</script>

RicohTrainingRegistration.CMS/Pages/Training/Model/_Edit.cshtml
@model RicohTrainingRegistration.CMS.Models.TrainingModelEditModel

<div id="modal1" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit Model</h4>
            </div>
            <form method="post" class="form-horizontal">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="control-label col-md-4">Model</label>
                                <div class="col-md-8">
                                    <div class="form-control-static"><span data-field="id"></span></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4">Name</label>
                                <div class="col-md-8">
                                    <div class="form-control-static"><span data-field="name"></span></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4">Entitled Free Training</label>
                                <div class="col-md-8">
                                    <div class="checkbox-list">
                                        <label class="checkbox-inline"><input type="checkbox" name="isFree" value="true" /> Yes</label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-4">Opened Days</label>
                                <div class="col-md-8">
                                    <input asp-for="OpenedDays" class="form-control open-days" />
                                    <span class="help-block">Days opened for registration</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>